volumes:
  sqldb-data:
  
services:
  frontend:
    build:
      context: ./DockerCourseFrontend/DockerCourseFrontend/.
    image: rafaspimenta/frontend
    container_name: frontend
    ports:
      - 1234:80
    networks:
      - frontend

  api:
    build:
      context: ./DockerCourseApi/. 
      dockerfile: DockerCourseApi/Dockerfile
    image: rafaspimenta/api
    container_name: api
    ports:
      - 7055:8080
    networks:
      - backend
      - frontend

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      - "ACCEPT_EULA=true"
      - "MSSQL_SA_PASSWORD=Dometrain#123"
    ports:
      - 1433:1433
    volumes:
      - sqldb-data:/var/opt/mssql
    networks:
      - backend
  
  database-seed:
    depends_on: [ database ]      
    build: 
      context: Database/
      dockerfile: Dockerfile
    container_name: database-seed
    networks:
      - backend    

networks:
  backend:
  frontend:  